name: Go

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    name: Build ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.8, 1.23.2]
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Build and Lint
      run: |
         go build ./...
         go vet -tests=false ./... # Specifically for examples without a corresponding identifier
  test:
    name: Text ${{ matrix.os }} | ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.22.8, 1.23.2]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Test on ${{ matrix.os }}
      run: |
         go test ./...
  boringcrypto:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.8, 1.23.2]
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Test
      run: |
         CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go test ./...
  vulncheck:
    name: Vulncheck ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.8, 1.23.2]
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Get govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash
    - name: Run govulncheck
      run: govulncheck ./...
      shell: bash
